spring:
  #默认配置文件
  profiles:
    active: dev
  #session绘会话存储类型
  session:
    store-type: hash_map
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  #thymeleaf的配置
  thymeleaf:
    mode: HTML
    prefix: classpath:/resources/
    suffix: .html
  devtools:
    restart:
      exclude: templates/**,static/**
  kafka:
    producer:
      bootstrap-servers: 192.168.2.101:9092
    consumer:
      group-id: fastsearch
      bootstrap-servers: 192.168.2.101:9092

#spring security
security:
  basic:
    #关闭http基本验证
    enabled: false
#禁用自带的错误页面
server:
  error:
    whitelabel:
      enabled: false

# qiniu 注意替换成自己申请的配置
qiniu:
  AccessKey: 5_o-1uXFijhRZEeSQXBl1n8O6EoR063xnYY5T_pt
  SecretKey: 2b2OIi1_l4gL0-1vpCDzgw_RE0s1_wJX40yTLdY6
  Bucket: fastsearch
  cdn:
    prefix: http://p8vm8po1c.bkt.clouddn.com/

elasticsearch:
  host: 192.168.2.81
  port: 9300
  cluster:
    name: fastsearch