spring:
  #默认配置文件
  profiles:
    active: dev
  #session绘会话存储类型
  session:
    store-type: hash_map
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  #thymeleaf的配置
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      exclude: templates/**,static/**


#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml

#spring security
security:
  basic:
    #关闭http基本验证
    enabled: false
#禁用自带的错误页面
server:
  error:
    whitelabel:
      enabled: false

